// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.virtualbox_6_1;

import lombok.var;
import virtualcomputerwindows.Exports;

@net.sf.jni4net.attributes.ClrInterface
public interface IEvent {

	//<generated-interface>
	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/VBoxEventType;")
	org.virtualbox_6_1_FixIt.VBoxEventType getType_FixIt();

	default VBoxEventType getType() {
		var type = Exports.convertEnum(getType_FixIt());
		for (var value : VBoxEventType.values())
			if (value.value() == type)
				return value;
		return null;
	}

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IEventSource;")
	IEventSource getSource();

	@net.sf.jni4net.attributes.ClrMethod("()I")
	int getWaitable();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void setProcessed();

	@net.sf.jni4net.attributes.ClrMethod("(I)I")
	int waitProcessed(int aTimeout);
	//</generated-interface>
}
