// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.virtualbox_6_1;

import lombok.var;
import system.Array;
import virtualcomputerwindows.Exports;

import java.util.List;

@net.sf.jni4net.attributes.ClrInterface
public interface IKeyboard {

	//<generated-interface>
	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getKeyboardLEDs_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IEventSource;")
	IEventSource getEventSource();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute1IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute2IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute3IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute4IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("(I)V")
	void putScancode(int aScancode);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/Array;)LSystem/UInt32;")
	int putScancodes_FixIt(system.Array aScancodes);

	default int putScancodes(List<Integer> scancodes) {
		var sc = new int[scancodes.size()];
		for (int i = 0; i < sc.length; i++)
			sc[i] = scancodes.get(i);
		return putScancodes_FixIt(Exports.convertArray_FixIt(sc));
	}

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void putCAD();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void releaseKeys();

	@net.sf.jni4net.attributes.ClrMethod("(III)V")
	void putUsageCode(int aUsageCode, int aUsagePage, int aKeyRelease);

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod1IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod2IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod3IKeyboard();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod4IKeyboard();
	//</generated-interface>
}
