// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.virtualbox_6_1;

@net.sf.jni4net.attributes.ClrInterface
public interface ISession {

	//<generated-interface>
	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/SessionState;")
	org.virtualbox_6_1.SessionState getState_FixIt();

	default org.virtualbox_6_1.SessionState getState() {
		return SessionState.Locked;
	}

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/SessionType;")
	org.virtualbox_6_1.SessionType getType_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	java.lang.String getName();

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
	void setName(java.lang.String aName);

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IMachine;")
	org.virtualbox_6_1.IMachine getMachine();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IConsole;")
	org.virtualbox_6_1.IConsole getConsole();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute1ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute2ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute3ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute4ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute5ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute6ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute7ISession();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute8ISession();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void unlockMachine();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod1ISession();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod2ISession();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod3ISession();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod4ISession();
	//</generated-interface>
}
