// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.virtualbox_6_1;

import virtualcomputerwindows.Exports;

@net.sf.jni4net.attributes.ClrInterface
public interface ISessionStateChangedEvent extends IMachineEvent, IEvent {

	//<generated-interface>
	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/VBoxEventType;")
	org.virtualbox_6_1_FixIt.VBoxEventType getType_FixIt();

	default VBoxEventType getType() {
		return VBoxEventType.values()[Exports.convertEnum(getType_FixIt())];
	}

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IEventSource;")
	IEventSource getSource();

	@net.sf.jni4net.attributes.ClrMethod("()I")
	int getWaitable();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void setProcessed();

	@net.sf.jni4net.attributes.ClrMethod("(I)I")
	int waitProcessed(int aTimeout);

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getMachineId();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/SessionState;")
	org.virtualbox_6_1_FixIt.SessionState getState_FixIt();

	default SessionState getState() {
		return SessionState.values()[Exports.convertEnum(getState_FixIt())];
	}
	//</generated-interface>
}
