// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package org.virtualbox_6_1;

import lombok.var;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@net.sf.jni4net.attributes.ClrInterface
public interface IVirtualBox {

	//<generated-interface>
	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getVersion();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getVersionNormalized();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getRevision();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getPackageType();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getAPIVersion();

	@net.sf.jni4net.attributes.ClrMethod("()J")
	long getAPIRevision();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getHomeFolder();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
	String getSettingsFilePath();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IHost;")
	IHost getHost();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/ISystemProperties;")
	ISystemProperties getSystemProperties();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getMachines_FixIt();

	default List<IMachine> getMachines() {
		var list = new ArrayList<IMachine>();
		var arr = getMachines_FixIt();
		for (int i = 0; i < arr.getLength(); i++)
			list.add((IMachine) arr.getItem(i));
		return Collections.unmodifiableList(list);
	}

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getMachineGroups_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getHardDisks_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getDVDImages_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getFloppyImages_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getProgressOperations_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getGuestOSTypes_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getSharedFolders_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IPerformanceCollector;")
	IPerformanceCollector getPerformanceCollector();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getDHCPServers_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getNATNetworks_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IEventSource;")
	IEventSource getEventSource();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IExtPackManager;")
	IExtPackManager getExtensionPackManager();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getInternalNetworks_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getGenericNetworkDrivers_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getCloudNetworks_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/ICloudProviderManager;")
	ICloudProviderManager getCloudProviderManager();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute1IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute2IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute3IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute4IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute5IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute6IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute7IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute8IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute9IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute10IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute11IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/UInt32;")
	int getInternalAndReservedAttribute12IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;LSystem/String;)LSystem/String;")
	String composeMachineFilename(String aName, String aGroup, String aCreateFlags, String aBaseFolder);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/Array;LSystem/String;LSystem/String;)Lorg/virtualbox_6_1/IMachine;")
	IMachine createMachine_FixIt(String aSettingsFile, String aName, system.Array aGroups, String aOSTypeId, String aFlags);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/IMachine;")
	IMachine openMachine(String aSettingsFile);

	@net.sf.jni4net.attributes.ClrMethod("(Lorg/virtualbox_6_1/IMachine;)V")
	void registerMachine(IMachine aMachine);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/IMachine;")
	IMachine findMachine(String aNameOrId);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/Array;)LSystem/Array;")
	system.Array getMachinesByGroups_FixIt(system.Array aGroups);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/Array;)LSystem/Array;")
	system.Array getMachineStates_FixIt(system.Array aMachines);

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IAppliance;")
	IAppliance createAppliance();

	@net.sf.jni4net.attributes.ClrMethod("()Lorg/virtualbox_6_1/IUnattended;")
	IUnattended createUnattendedInstaller();

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;Lorg/virtualbox_6_1_FixIt/AccessMode;Lorg/virtualbox_6_1/DeviceType;)Lorg/virtualbox_6_1/IMedium;")
	IMedium createMedium_FixIt(String aFormat, String aLocation, org.virtualbox_6_1_FixIt.AccessMode aAccessMode, org.virtualbox_6_1_FixIt.DeviceType aADeviceTypeType);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;Lorg/virtualbox_6_1/DeviceType;Lorg/virtualbox_6_1_FixIt/AccessMode;I)Lorg/virtualbox_6_1/IMedium;")
	IMedium openMedium_FixIt(String aLocation, org.virtualbox_6_1_FixIt.DeviceType aDeviceType, org.virtualbox_6_1_FixIt.AccessMode aAccessMode, int aForceNewUuid);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/IGuestOSType;")
	IGuestOSType getGuestOSType(String aId);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;IILSystem/String;)V")
	void createSharedFolder(String aName, String aHostPath, int aWritable, int aAutoMount, String aAutoMountPoint);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
	void removeSharedFolder(String aName);

	@net.sf.jni4net.attributes.ClrMethod("()LSystem/Array;")
	system.Array getExtraDataKeys_FixIt();

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
	String getExtraData(String aKey);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)V")
	void setExtraData(String aKey, String aValue);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
	void setSettingsSecret(String aPassword);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/IDHCPServer;")
	IDHCPServer createDHCPServer(String aName);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/IDHCPServer;")
	IDHCPServer findDHCPServerByNetworkName(String aName);

	@net.sf.jni4net.attributes.ClrMethod("(Lorg/virtualbox_6_1/IDHCPServer;)V")
	void removeDHCPServer(IDHCPServer aServer);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/INATNetwork;")
	INATNetwork createNATNetwork(String aNetworkName);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/INATNetwork;")
	INATNetwork findNATNetworkByName(String aNetworkName);

	@net.sf.jni4net.attributes.ClrMethod("(Lorg/virtualbox_6_1/INATNetwork;)V")
	void removeNATNetwork(INATNetwork aNetwork);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/ICloudNetwork;")
	ICloudNetwork createCloudNetwork(String aNetworkName);

	@net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Lorg/virtualbox_6_1/ICloudNetwork;")
	ICloudNetwork findCloudNetworkByName(String aNetworkName);

	@net.sf.jni4net.attributes.ClrMethod("(Lorg/virtualbox_6_1/ICloudNetwork;)V")
	void removeCloudNetwork(ICloudNetwork aNetwork);

	@net.sf.jni4net.attributes.ClrMethod("(Lorg/virtualbox_6_1/FirmwareType;LSystem/String;LSystem/String;LSystem/String;)I")
	int checkFirmwarePresent_FixIt(org.virtualbox_6_1_FixIt.FirmwareType aFirmwareType, String aVersion, net.sf.jni4net.Out<String> aUrl, net.sf.jni4net.Out<String> aFile);

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod1IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod2IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod3IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod4IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod5IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod6IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod7IVirtualBox();

	@net.sf.jni4net.attributes.ClrMethod("()V")
	void internalAndReservedMethod8IVirtualBox();
	//</generated-interface>
}
