name: VirtualComputer
main: sznp.virtualcomputer.PluginMain
version: '3.0'
author: 'NorbiPeti'
commands:
    computer:
        usage: Use /computer start|stop|reset|key|mouse|input|fix
        aliases: c
api-version: '1.13'
depend:
    - Chroma-Core